### ISSUE TITLE
ESA Biomass Climate Change Initiative (Biomass_cci)

### ISSUE THREAD

**Issue by ckoven** [rubisco-sfa/ILAMB-Data#19] opened 2022-05-13 19:42 UTC
Global datasets of forest above-ground biomass for the years 2010, 2017 and 2018, v2

From description:
>  The maps are derived from a combination of data, depending on the year, from the [Copernicus Sentinel-1 mission](http://www.esa.int/Applications/Observing_the_Earth/Copernicus/Sentinel-1), [Envisat’s ASAR instrument](https://earth.esa.int/eogateway/instruments/asar) and [JAXA’s Advanced Land Observing Satellite (ALOS-1 and ALOS-2)](https://global.jaxa.jp/projects/sat/alos2/), along with additional information from Earth observation sources.

more info here: https://climate.esa.int/en/news-events/maps-improve-forest-biomass-estimates/

data available at: http://dx.doi.org/10.5285/84403d09cef3485883158f4df2989b0c

**Comment by nocollier** [comment] 2022-05-13 19:59
We have a formatting script from @mmu2019 for this already in the repository [here](https://github.com/rubisco-sfa/ILAMB-Data/blob/master/ESACCI/read-biomass-ESACCI.py), although there are a few things that we could cleanup. The main obstacle to including it is that the data is high resolution (100m). A datafile from a single year is larger than our whole reference dataset collection and then creates practical problems when running through ILAMB. Coarsening it is a clear solution, but it is tricky as the dataset so large that I couldn't find a method.

**Comment by nocollier** [comment] 2022-05-13 20:10
We could test out xarray's chunking and the [coarsen](https://xarray.pydata.org/en/stable/generated/xarray.DataArray.coarsen.html) function. Examples shown are in the `time` dimension but presumably could be applied to latitude and longitude either combined or in sequence.

**Comment by ckoven** [comment] 2022-05-13 20:12
wow I didn't even know that the coarsen function was a thing. cool.

**Comment by nocollier** [comment] 2022-05-16 19:15
FYI, this worked on one of the 17Gb files:
```python
import xarray as xr

cs = 563 # hand calculated number of rows/cols that ~0.5 degrees                                         
ds = xr.open_dataset("ESACCI-BIOMASS-L4-AGB-MERGED-100m-2018-fv2.0.nc",
                     chunks={'lat':10*cs,'lon':10*cs}) # chunks ~120 Mb                                  
da = ds['agb']
c = da.coarsen({'lat':cs,'lon':cs},boundary='pad').mean()
c.to_netcdf('out.nc')
```
Will poke around a little more and see if I can record peak memory and timing. The more high resolution data that is out there, the better we will need to be at working with it.

**Comment by mmu2019** [comment] 2022-05-16 19:30
Hi Nate,

That is really helpful. The original code took so much time to process this
data for one single year. I wonder if it is still a separate code to
pre-process data only instead of combining it with ILAMB package. The
similar issue is to process OSU (Oregon State University) biomass. Does
this modified code work with OSU biomass? Thanks.

Mingquan

**Comment by nocollier** [comment] 2022-05-16 22:52
In theory yes, but hold up while I sort it out. I managed to get some profiling information on the above snippet:

```
peak memory: 7732.23 MiB, increment: 7603.69 MiB
CPU times: user 34min 52s, sys: 20min 27s, total: 55min 20s
Wall time: 41min 8s
```

I am a little suspicious of this since I thought I was chunking by 120 Mb. The mean() and coarsen() operators will consume more memory than what is read in the chunk, but a 7.6 Gb peak is a surprise. The file is 17 Gb, but there are 2 variables: the biomass and the standard error. So a reduction from 17/2=8.5 Gb to 7.6 doesn't seem that good. Just trying to make sure I know what I am doing before we replicate it on other datasets.

**Comment by nocollier** [comment] 2022-05-17 12:16
Ok, I can confirm that the above code snippet is working as intended. In that example, I found that a 563x563 pixel square from the original file is roughly 0.5x0.5 degrees. So I tried chunking a 10x10 grid of these at a time and the memory consumed was high. Moving to a 5x5 grid of these increased runtime substantially but also reduced the peak memory.

```
peak memory: 3301.84 MiB, increment: 3192.85 MiB
CPU times: user 1h 21min 37s, sys: 30min 39s, total: 1h 52min 17s
Wall time: 1h 45min 19s
```

The tricky part is that you will have to experiment with it on your own system. In this case I was on a large memory machine (250 Gb) and have more flexibility. @mmu2019 my plan now is to write a script for how I would encode this dataset and let it serve as a sample for future large datasets. Keep your eyes here for progress.

**Comment by nocollier** [comment] 2022-05-17 14:41
Some topics for discussion/information:

* The dataset does provide uncertainty estimates
* They have data for 2010, 2017, and 2018.
* What data do we encode? The 2010-2017 gap could be problematic for the ILAMB code. I may have some implicit assumptions about the time difference being uniform in the dataset.
* Also, models are not currently run out through 2017 and 2018. The data from those years would not be used in any of our current comparisons.
* To what does this dataset compare from the model? We use `cVeg` in current biomass comparisons, but the dataset reports 'the mass, expressed as oven-dry weight of the woody parts (stem, bark, branches and twigs) of all living trees excluding stump and roots'. Just wanted to make sure that `cVeg` was still the most appropriate model variable.

We can also discuss on a call @climate-dude @ckoven @dlawrenncar

**Comment by ckoven** [comment] 2022-05-17 15:51
good question @nocollier. `cVeg` includes root biomass, so ideally best not to use it.  I think in principle the right thing would be either `cWood` or `cStem`.  I'm not sure if either `cWood` or `cStem` includes coarse roots, I believe they are both the same thing and don't include coarse roots, since both have long names of `stem_mass_content_of_carbon`.

**Comment by ckoven** [comment] 2022-05-17 16:16
Also @nocollier to the question about what year to use, the dataset warns against interpreting the difference from one year to the next as a real change in biomass, so I would suggest we just pick a single year and make that the benchmark.  Since as you say, the transition in CMIP6 from historical to future scenarios is in 2015, I would vote that we just use 2010 so that we can use the historical experiment runs.

**Comment by mmu2019** [comment] 2022-05-17 16:57
For this issue, I think we have talked about it before. cVeg includes
everything, like tree, grass etc, for total biomass carbon
(aboveground+belowground), however most of the observations are just for
trees, and some are just for aboveground biomass. There is another variable
"treeFrac" from most models but not from all the models.  We can convert
cVeg multiplied by treeFrac to get biomass for trees only. The ratio for
belowground and aboveground biomass is about 0.2 roughly in the
observation. We can use this number to further constrain the model cVeg in
order to better compare with the observations.

**Comment by nocollier** [comment] 2022-05-17 20:16
Ok, this script is now added, see 4fa446b and [here](https://www.climatemodeling.org/~nate/ILAMB-Test/comparisons/cVeg.png) for a comparison to other biomass products we support. Note that I believe the original source does not apply a land mask and so you get large squares of 0 near any kind of vegetation. The bias works out fine, just looks a little odd. This could be an artifact of the coarsening process too I guess.

@mmu2019 you can try following the approach [here](https://github.com/rubisco-sfa/ILAMB-Data/blob/master/ESACCI/convert.py) for the OSU dataset. Let me know how it goes. You will have to play around with the `ntile` variable depending on available memory.

Regarding comparing the biomass datasets to `0.8 * cVeg * treeFrac`, we should discuss this again. I knew I had heard you present something of the sort before but I didn't recall the details. I wonder if the group collectively feels that this is better? I am not an expert here, but the 20% feels somewhat arbitrary. Is there a paper reference for that number? The other thing that becomes difficult is that, as you said, not all models give `treeFrac`. I found that the BCC, NorESM, MIROC for CMIP6 do not. So then, how do we communicate that for some models you are seeing a comparison to `cVeg` and some this other factor? Maybe we can come up with a method.

**Comment by nocollier** [comment] 2022-05-26 16:59
I am closing this issue with c577133, see the ILAMB [CMIP6 results](https://www.ilamb.org/CMIP6/historical/EcosystemandCarbonCycle/Biomass/ESACCI/ESACCI.html). However, we should discuss the above point.

**Closed by nocollier** 2022-05-26 16:59 UTC
